Add README PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> & "C:/Users/User/Desktop/ЯПрактикум/Проект №6/.venv/Scripts/Activate.ps1" (.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> git status Last commands done (2 commands done):    pick af761ee # Commit linreg    pick 2faa82c # Add README No commands remaining. You are currently rebasing branch 'main' on 'c07c26b'.   (all conflicts fixed: run "git rebase --continue")
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   README.md

(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6>
                                                       git push -u origin main
To https://github.com/shocknik/predicting_customer_churn.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/shocknik/predicting_customer_churn.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> & "C:/Users/User/Desktop/ЯПрактикум/Проект №6/.venv/Scripts/Activate.ps1"
(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> git status
Last commands done (2 commands done):
   pick af761ee # Commit linreg
   pick 2faa82c # Add README
No commands remaining.
You are currently rebasing branch 'main' on 'c07c26b'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   README.md

(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6>
                                                       git push -u origin main
To https://github.com/shocknik/predicting_customer_churn.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/shocknik/predicting_customer_churn.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6>

hint: Updates were rejected because a pushed branch tip is behind its
rem[Oote
hint: counterpart. If you want to integrate the remote changes, use 'git
pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.
(.venv) PS C:\Users\User\Desktop\ЯПрактикум\Проект №6> with '#' will be ignored, and an empty message aborts the commit.